Enable IntelliSense prediction by default
lzybkr/PSReadLine pull request #3351
Opened 2022-06-21 21:16 UTC by daxian-dbw

# PR Summary

Enable intellisense prediction by default:
- when VT is not supported, `PredictionSource` is set to `None` by default
- when VT is supported and it's running with PowerShell 7.2+, `PredictionSource` is set to `HistoryAndPlugin` by default
- when VT is supported and it's running with PowerShell prior to 7.2, `PredictionSource` is set to `History` by default

## PR Checklist

- [x] PR has a meaningful title
    - Use the present tense and imperative mood when describing your changes
- [x] Summarized changes
- [ ] Make sure you've added one or more new tests
- [x] Make sure you've tested these changes in terminals that PowerShell is commonly used in (i.e. conhost.exe, Windows Terminal, Visual Studio Code Integrated Terminal, etc.)
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] Documentation needed at [PowerShell-Docs](https://github.com/MicrosoftDocs/PowerShell-Docs)
        - [x] Doc Issue filed: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/8943

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/PowerShell/PSReadLine/pull/3351)

2022-06-21 22:05 UTC, daxian-dbw commented
@andschwa Can you please review this PR when you get a chance? Thanks!

2022-06-22 17:22 UTC, andyleejordan requested changes

2022-06-22 17:22 UTC, andyleejordan commented on PSReadLine/Cmdlets.cs
> +                : Environment.Version.Major < 6
Just double-checking here @daxian-dbw, your PR description says:

> when VT is supported and it's running with PowerShell 7.2+, PredictionSource is set to HistoryAndPlugin by default
when VT is supported and it's running with PowerShell prior to 7.2, PredictionSource is set to History by default

But this is checking `Version.Major < 6`

So 7 and up (theoretically including 7.0 and 7.1, not just 7.2+, also any old versions of 6 that may still be out there) are going to be `HistoryAndPlugin`. Is that what you intend?

2022-06-22 17:28 UTC, daxian-dbw commented on PSReadLine/Cmdlets.cs
> +                : Environment.Version.Major < 6
It's `Environment.Version.Major`, meaning the major version of the .NET Core. PowerShell 7.2 comes with .NET 6, so if `Environment.Version.Major < 6`, the PowerShell version is lower than 7.2, and we will use `History` as the default prediction source.

2022-06-22 17:34 UTC, andschwa commented on PSReadLine/Cmdlets.cs
> +                : Environment.Version.Major < 6
Got it, got it. Thanks for checking!

2022-06-22 17:34 UTC, andyleejordan approved these changes

2022-06-22 19:15 UTC, daxian-dbw commented
@andschwa Thanks for the review!

2022-06-22 19:15 UTC, merged